version: "3.5"
services:
  tdemo:
    container_name: tdemo
    image: leowmjw/temporalite
    networks:
      - tdemo-network
    ports:
      - "7233:7233"
  tdemo-admin-tools:
    container_name: tdemo-admin-tools
    depends_on:
      - tdemo
    environment:
      - TEMPORAL_CLI_ADDRESS=tdemo:7233
    image: temporalio/admin-tools:1.13.1
    networks:
      - tdemo-network
    stdin_open: true
    tty: true
  tdemo-web:
    container_name: tdemo-web
    depends_on:
      - tdemo
    environment:
      - TEMPORAL_GRPC_ENDPOINT=tdemo:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/web:1.13.0
    networks:
      - tdemo-network
    ports:
      - "8088:8088"
networks:
  tdemo-network:
    driver: bridge
    name: tdemo-network
